<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LabelStudio.Printing\LabelStudio.Printing.csproj" />
    <ProjectReference Include="..\LabelStudio.Rendering\LabelStudio.Rendering.csproj" />
  </ItemGroup>

</Project>